version: '3.8'

services:
  forecast-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs 